from .consultant_admin import ConsultantAdmin
from .contract_admin import ContractAdmin, ContractExtensionAdmin
from .department_admin import DepartmentAdmin
from .employee_admin import EmployeeAdmin, SupervisorAdmin
from .key_performance_area_admin import KeyPerformanceAreaAdmin
from .pi_admin import PiAdmin
from .performance_assessment_admin import PerformanceAssessmentAdmin
from .performance_imp_plan_admin import PerformanceImpPlanAdmin
from .performance_imp_plan_admin import ImprovementObjectivesAdmin
from .professional_skills_admin import ProfessionalSkillsAdmin
